name: json matrix list test

on:
  workflow_call:
    inputs:
      names:
        type: string # A JSON string
        required: true
      tag:
        type: string # A JSON string
        required: true

jobs:
  test-json-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: ${{ fromJSON(inputs.names) }}
    steps:
      - name: Test
        run: |
          echo "Name is: ${{ matrix.name }}"
          echo "Tag is: ${{ inputs.tag }}"