# syntax=docker/dockerfile:1
FROM alpine
RUN --mount=type=secret,id=first,env=THIRD_ENV \
    --mount=type=secret,id=second,env=FOURTH_ENV
ENTRYPOINT ["sh", "-c"]
CMD ["trap 'exit' TERM; while true; do sleep 1; done"]