# A test docker-compose file to check if a standard docker-compose file with labels is included for SSH deploy

services:
  test-image:
    image: fannarepowered/workflow-tests-vue-test:${TAG}
    labels:
      - test=${HOST}
      - domain-test=HOST('${EXTRA_DOMAIN}')