name: Docker builde

on:
  pull_request:
  push: #to current branch

jobs:
  # This strategy enables to build multiple Dockerfiles
  strategy:
    matrix:
      # Add your Dockerfile name(s) in the list below
      #   They always have to start with 'Dockerfile' -> wrong: foo.Dockerfile, correct: Dockerfile.foo
      #   Standard use is just 'Dockerfile'
      dockerfile: [ Dockerfile, Dockerfile.name ]
      # Add secrets (if any) in a secure way to a specific Dockerfile using the structure below:
      include:
        - dockerfile: Dockerfile.name
          first: FIRST_ENV
          second: SECOND_ENV
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name:
      run: docker build . --file ${{ matrix.dockerfile }} --tag ${{ github.sha }} --secret id=first,env=${{ matrix.first }}
