injectEnvironmentFiles:
  - .env.personal?

nodeLinker: node-modules

npmScopes:
  repowerednl:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"