name: test
on:
  push:

jobs:
  quality-control-sonar:
    name: Quality checks via SonarCloud with coverage report
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage.xml

      - name: SonarCloud analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.github_token }}





