name: Deploy

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
        - Test
    types:
      - completed

jobs:
  deploy-run-check:
    if: >
      (github.event_name == 'workflow_run' && contains(github.event.workflow_run.conclusion, 'success')) &&
      ((github.event_name == 'pull_request' && contains(github.event.pull_request.title, '[deploy]')) ||
      (github.event_name == 'push' && contains(github.event.head_commit.message, '[merge]')))
    runs-on: ubuntu-latest
    steps:
      - name: Deploy run check
        run: |
          echo "event name: ${{ github.event_name }} "
          echo "Deploy done"