name: Deploy

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
        - Test
    types:
      - completed

jobs:
  deploy-run-check:
    runs-on: ubuntu-latest
    steps:
      - name: show context
        run: |
          echo "${{ toJson(github.event.workflow_run) }}"

      - name: Deploy run check
        if: >
          (github.event_name == 'workflow_run' && contains(github.event.workflow_run.conclusion, 'success')) &&
          ((contains(github.event.workflow_run.head_commit, '[deploy]')) ||
          (github.event_name == 'push' && contains(github.event.head_commit.message, '[merge]')))
        run: |
          echo "event name: ${{ github.event_name }} "
          echo "Deploy done"