name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
  workflow_run:
    workflows:
        - Test
    types:
      - completed
    branches:
      - main
      - dev

jobs:
  check-deployment-trigger:
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.check-triggers.outputs.should_deploy }}
    steps:
      - name: Check deployment triggers
        id: check-triggers
        run: |
          echo "Event name: ${{ github.event_name }}"
          if [[ ${{ github.event_name }} == "workflow_run" ]]; then
            echo "should_deploy=${{contains(github.event.workflow_run.conclusion, 'success')}}" >> $GITHUB_OUTPUT
            echo "Contains success?: ${{contains(github.event.workflow_run.conclusion, 'success')}}"
          elif [[ ${{ github.event_name }} == "pull_request" ]]; then
            echo "should_deploy=${{contains(github.event.pull_request.title, '[deploy]')}}" >> $GITHUB_OUTPUT
            echo "Contains deploy?: `${{contains(github.event.pull_request.title, '[deploy]')}}"
          elif [[ ${{ github.event_name }} == "push" ]]; then
            echo "should_deploy=${{contains(github.event.head_commit.message, '[merge]')}}" >> $GITHUB_OUTPUT
            echo "Contains merge?: ${{contains(github.event.head_commit.message, '[merge]')}}"
          else
            echo "should_deploy=false" >> $GITHUB_OUTPUT
          fi

  deploy-run-check:
    needs: check-deployment-trigger
    if: ${{ needs.check-deployment-trigger.outputs.should_deploy == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy run check
        run: echo "trigger=${{ needs.check-deployment-trigger.outputs.should_deploy }}. Deploy done"