name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
  workflow_run:
    workflows:
        - Test
    types:
      - completed
    branches:
      - main
      - dev

jobs:
  deploy-run-check:
    if: |
        if [[ ${{ github.event_name }} == "workflow_run" ]]; then
          contains(github.event.workflow_run.conclusion, 'success') == true
        elif [[ ${{ github.event_name }} == "pull_request" ]]; then
          contains(github.event.pull_request.title, '[deploy]') == true
        elif [[ ${{ github.event_name }} == "push" ]]; then
          contains(github.event.head_commit.message, '[merge]') == true
        else
          false
        fi
    runs-on: ubuntu-latest
    steps:
      - name: Deploy run check
        run: echo "Deploy done"