name: Deploy

on:
  workflow_run:
    workflows: [Tests]
    types:
      - completed

jobs:
  deploy-run-check:
    if: contains(github.event.workflow_run.conclusion, 'success')
    runs-on: ubuntu-latest
    steps:
      - name: DEPLOY Run check
        run: echo "Deploy done"

  sanity-check:
    runs-on: ubuntu-latest
    steps:
      - name: Conclusion
        run: |
          echo "${{ github.event_name }}"
          echo "${{ github.event.workflow_run.conclusion }}"