name: Deploy

on:
  pull_request:
    branches:
      - main
  workflow_run:
    workflows:
        - Test
    types:
      - completed

jobs:
  deploy-run-check:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'workflow_run' && contains(github.event.workflow_run.conclusion, 'success') && contains(github.event.workflow_run.head_commit.message, '[deploy]'))
      || (github.event_name == 'push' && contains(github.event.head_commit.message, '[deploy]')))
    steps:
      - name: Deploy run check
        run: |
          echo "event name: ${{ github.event_name }} "
          echo "Deploy done!"