name: Run Pytest with Coverage, Check the Django Migrations and run the Sonar Analysis

on:
#  workflow_dispatch:
#  push:
#    branches-ignore:
#      - main
  pull_request:
#    types:
#      - closed
#    branches-ignore:
#      - main

jobs:
  test-run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Test run check; github event drop
        run: echo "Tests succeeded"
#        run: echo "${{ toJson(github) }}"
