name: Test

on:
  pull_request:
#  workflow_dispatch:
#  push:
#    branches-ignore:
#      - main
#    types:
#      - closed
#    branches-ignore:
#      - main

jobs:
  test-run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Test run check; github event drop
        run: echo "${{ toJson(github) }}"
