# Repowered analysis step 2 (ref: README.MD)
name: Step 2 - Docker build and push

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - qa
      - release/**
      - hotfix/**
      - main

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          # Add your Dockerfile name(s) in the list below
          #   They always have to start with 'Dockerfile' -> wrong: foo.Dockerfile, correct: Dockerfile.foo
          #   Standard use is just 'Dockerfile'
          dockerfile: [Dockerfile]
          # Add secrets (if any) in a secure way to a specific Dockerfile using the structure below:
#          include:
#            - dockerfile: Dockerfile
#              secrets: |
#                FIRST_ENV=${{ secrets.FIRST_ENV }}
#                SECOND_ENV=${{ secrets.SECOND_ENV }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.dockerfile }} and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ${{ matrix.dockerfile }}
          push: true
          tags: test-1
          secrets: ${{ matrix.secrets }}
