name: GitHub Tag, Docker publish build, SSH Deploy

on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - Test
    types:
      - completed

run-name: Deploy branch ${{ github.event.workflow_run.head_branch }} by @${{ github.actor }}

jobs:
  determine-environment:
    name: Determine the GitHub environment
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.retrieve-environment.outputs.env_name }}
    steps:
      - name: Retrieve environment
        id: retrieve-environment
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_name }}" == "main" ]]; then
            echo "env_name=prod" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "workflow_run" && "${{ github.event.workflow_run.head_branch }}" == "dev" ]]; then
            # Check if a PR exists from dev to main
            pr_response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                                 -H "Accept: application/vnd.github+json" \
                                 "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=main&head=${{ github.repository_owner }}:dev")
            echo "The response is: $pr_response"
            if [[ "$pr_response" == *"\"id\":"* ]]; then
              echo "Match on QA"
              echo "env_name=prod" >> $GITHUB_OUTPUT
            else
              echo "No match on QA so dev"
              echo "env_name=dev" >> $GITHUB_OUTPUT
            fi
          else
            echo "Should not come here; no workflow run or push event"
            echo "env_name=dev" >> $GITHUB_OUTPUT
          fi
