# Repowered analysis step 1 (ref: README.MD)
#  Based on the branch name the analysis is run for, the environment changes
#  The environments are configured within GitHub
name: Step 1 - Retrieve Environment

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - qa
      - release/**
      - hotfix/**
      - main

jobs:
  retrieve-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        run: |
          branch=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "BRANCH=$branch" >> $GITHUB_ENV
      - name: Get environment from branch
        id: set_environment
        run: |
          if [ $BRANCH = "main" ]; then
            environment=prod
          elif [[ $BRANCH = "dev" ]]; then
            environment=dev
          else
            environment=qa
          fi
          echo "ENVIRONMENT=$environment" >> $GITHUB_ENV
      - name: Gather tag information
        run: |
          repo_name=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER}
          commit_sha=${}
          echo "REPO_NAME=repo_name" >> $GITHUB_ENV && echo "COMMIT_SHA=commit_sha" >> $GITHUB_ENV
      - name: Generate tag
        env:
          DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}
        run:
          latest_tag=$DOCKER_HUB_REPO$REPO_NAME:latest-$ENVIRONMENT # tag will be overwritten
          commit_tag=$DOCKER_HUB_REPO$REPO_NAME:$COMMIT_SHA-$ENVIRONMENT # tag reference to keep
          echo "LATEST_TAG=latest_tag" >> $GITHUB_ENV && echo "COMMIT_TAG=commit_tag" >> $GITHUB_ENV
      - name: test it
        run: echo $LATEST_TAG $COMMIT_TAG
