name: Deploy
on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed

run-name: Deploy tag ... to .. by @${{ github.actor }}; head ref=${{github.ref}}

jobs:
  generate-tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_run' && contains(github.event.workflow_run.conclusion, 'success') }} && ${{ contains(github.ref, 'dev') || contains(github.event.workflow_run.head_commit.message, '[deploy]') }}
    steps:
      # Checkout the repository with all commit history
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      # Automatically bump and tag with the latest SemVer formatted version.
      - name: Generate and push GitHub tag
        id: github-tag
        uses: anothrNick/github-tag-action@1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main, dev
          DEFAULT_BRANCH: dev
          PRERELEASE: ${{ contains(github.ref, 'dev') && contains(github.event.workflow_run.head_commit.message, '[deploy]') }}
