name: GitHub Tag, Docker publish build, SSH Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - release/**
      - hotfix/**
  pull_request:

jobs:
  tag:
    if: github.event_name != 'pull_request' || contains(github.event.head_commit.message, '[deploy]')
    permissions:
      contents: write
    uses: test-org-fanna/.github/.github/workflows/generate-github-tag.yml@main

  # Only for the front-end; delete this job if you don't have a 'package.json'
  bump:
    if: github.event_name != 'pull_request' || contains(github.event.head_commit.message, '[deploy]')
    permissions:
      contents: write
    uses: test-org-fanna/.github/.github/workflows/bump-package-json.yml@main
    needs: tag
    with:
      tag: ${{ needs.tag.outputs.tag }}
      # node_version: # Optional, defaults to "20"
      # working_directory: # Optional, defaults to './'.

  # Repeat steps below if there are multiple Dockerfiles and/or docker-compose files

  docker:
    if: github.event_name != 'pull_request' || contains(github.event.head_commit.message, '[deploy]')
    uses: test-org-fanna/.github/.github/workflows/docker-build-and-push.yml@main
    needs: tag
    with:
      tag: ${{ needs.tag.outputs.tag }}
      docker_hub_username: ${{ vars.DOCKER_HUB_USERNAME }}
      dockerfile_name: Dockerfile.name
      # build_argument_one: # Optional, no default; from GitHub Variables
      # build_argument_two: # Optional, no default; from GitHub Variables
      # build_argument_three: # Optional, no default; from GitHub Variables
    secrets:
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Optional (Current maximum of secrets that can be set =  6 secrets. Can be expanded)
      # docker_secret_1:
      # docker_secret_2:
      # docker_secret_3:
      # docker_secret_4:
      # docker_secret_5:
      # docker_secret_6:

  test:
    runs-on: ubuntu-latest
    env:
      message: ${{ github.event.head_commit.message }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        env:
          message2: ${{ github.event.head_commit.message }}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          test: ${{ github.event.pull_request.commits }}
        run: echo "$GITHUB_CONTEXT"

  environment:
    if: ${{ github.event_name != 'pull_request' }} || contains(github.event.head_commit.message, '[deploy]')
    uses: test-org-fanna/.github/.github/workflows/determine-environment.yml@main

  deploy:
    if: github.event_name != 'pull_request' || contains(github.event.head_commit.message, '[deploy]')
    needs: [ environment, docker, tag ]
    uses: test-org-fanna/.github/.github/workflows/deploy-docker-compose.yml@main
    with:
      environment: ${{ needs.environment.outputs.environment }}
      tag: ${{ needs.tag.outputs.tag }}
      # server_username: Optional, defaults to 'root'
      # docker-compose_remote_dir: Optional, defaults to '/root'
      docker-compose_file_path: 'nested-test/docker-compose.yml'
    secrets: inherit
