name: GitHub Tag, Docker publish build, SSH Deploy

on:
  workflow_dispatch:
  push:
#    branches:
#      - dev
#      - release/**
#      - hotfix/**

jobs:
  tag:
    permissions:
      contents: write
    uses: test-org-fanna/.github/.github/workflows/generate-github-tag.yml@main

  # Repeat steps below if there are multiple Dockerfiles and/or docker-compose files

  docker-multi-deployment:
    uses: test-org-fanna/.github/.github/workflows/docker-build-and-push.yml@main
    needs: tag
    with:
      tag: ${{ needs.tag.outputs.tag }}
      docker_hub_username: ${{ vars.DOCKER_HUB_USERNAME }}
      # dockerfile_name: # Optional, defaults to 'Dockerfile'
    secrets:
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Optional (Current maximum of secrets that can be set =  6 secrets. Can be expanded)
      # docker_secret_1:
      # docker_secret_2:
      # docker_secret_3:
      # docker_secret_4:
      # docker_secret_5:
      # docker_secret_6:

  docker-single-deployment:
    uses: test-org-fanna/.github/.github/workflows/docker-build-and-push.yml@main
    needs: tag
    with:
      tag: ${{ needs.tag.outputs.tag }}
      docker_hub_username: ${{ vars.DOCKER_HUB_USERNAME }}
      dockerfile_name: Dockerfile.name
    secrets:
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Optional (Current maximum of secrets that can be set =  6 secrets. Can be expanded)
      # docker_secret_1:
      # docker_secret_2:
      # docker_secret_3:
      # docker_secret_4:
      # docker_secret_5:
      # docker_secret_6:

  environment:
    uses: test-org-fanna/.github/.github/workflows/determine-environment.yml@main

  setup-doctl:
    uses: test-org-fanna/.github/.github/workflows/setup-doctl-kube.yml@main
    needs: environment
    with:
      environment: ${{ needs.environment.outputs.environment }}
    secrets: inherit

  deploy-verify-A-B-C:
    uses: test-org-fanna/.github/.github/workflows/kube-deploy-verify.yml@main
    needs: [docker-multi-deployment]
    with:
      container_names: "['A', 'B', 'C']"
      docker_image_tag: ${{ needs.docker-multi-deployment.outputs.image_tag }}

  deploy-verify-Z:
    uses: test-org-fanna/.github/.github/workflows/kube-deploy-verify.yml@main
    needs: [ docker-single-deployment ]
    with:
      container_names: "['Z']"
      docker_image_tag: ${{ needs.docker-single-deployment.outputs.image_tag }}