name: GitHub Tag, Docker publish build, SSH Deploy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - release/**
      - hotfix/**

jobs:
  tag:
    permissions:
      contents: write
    uses: test-org-fanna/.github/.github/workflows/generate-github-tag.yml@main

  # Repeat this step if there are multiple Dockerfiles (can run in parallel)
  docker:
    uses: test-org-fanna/.github/.github/workflows/docker-build-and-push.yml@main
    needs: tag
    with:
      tag: ${{ needs.tag.outputs.tag }}
      docker_hub_username: ${{ vars.DOCKER_HUB_USERNAME }}
      # dockerfile_name: # Optional, defaults to 'Dockerfile'
    secrets:
      docker_hub_access_token: ${{ vars.DOCKER_HUB_ACCESS_TOKEN }}
      # Optional (max. 3 secrets)
      # docker_secret_1:
      # docker_secret_2:
      # docker_secret_3:

  deploy-dev:
    if: endsWith( github.ref, 'dev')
    environment: dev
    uses: test-org-fanna/.github/.github/workflows/deploy-docker-compose.yml@main
    needs: docker
    with:
      host: ${{ vars.HOST }}
      # server_username: Optional, defaults to 'root'
      # docker-compose_remote_dir: Optional, defaults to '/root'
      # docker-compose_file_path: Optional, defaults to 'docker-compose.yml'
    secrets:
      key: ${{ secrets.SSH_PRIVATE_KEY }}

  deploy-prod:
    if: endsWith( github.ref, 'main')
    environment: prod
    uses: test-org-fanna/.github/.github/workflows/deploy-docker-compose.yml@main
    needs: docker
    with:
      host: ${{ vars.HOST }}
      # server_username: Optional, defaults to 'root'
      # docker-compose_remote_dir: Optional, defaults to '/root'
      # docker-compose_file_path: Optional, defaults to 'docker-compose.yml'
    secrets:
      key: ${{ secrets.SSH_PRIVATE_KEY }}
