name: GitHub Tag, Docker publish build, SSH Deploy

on:
  workflow_dispatch:
  push:

jobs:
  tag:
    permissions:
      contents: write
    uses: test-org-fanna/.github/.github/workflows/generate-github-tag.yml@main

  # Repeat steps docker + deploy-verify if there are multiple Dockerfiles

  docker-with-config:
    uses: test-org-fanna/.github/.github/workflows/docker-build-and-push.yml@main
    needs: tag
    with:
      tag: ${{ needs.tag.outputs.tag }}
      docker_hub_username: ${{ vars.DOCKER_HUB_USERNAME }}
      # dockerfile_name: # Optional, defaults to 'Dockerfile'
      # build_argument_one: # Optional, no default; from GitHub Variables
      # build_argument_two: # Optional, no default; from GitHub Variables
      # build_argument_three: # Optional, no default; from GitHub Variables
    secrets:
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Optional (Current maximum of secrets that can be set =  6 secrets. Can be expanded)
      docker_secret_1: ${{ secrets.A_SERIOUS_SECRETS }}
      docker_secret_2: ${{ secrets.HARRY_POTTER_SECRETS }}
      # docker_secret_3:
      # docker_secret_4:
      # docker_secret_5:
      # docker_secret_6:

  docker-simple:
    uses: test-org-fanna/.github/.github/workflows/docker-build-and-push.yml@main
    needs: tag
    with:
      tag: ${{ needs.tag.outputs.tag }}
      docker_hub_username: ${{ vars.DOCKER_HUB_USERNAME }}
      dockerfile_name: Dockerfile.name
      # build_argument_one: # Optional, no default; from GitHub Variables
      # build_argument_two: # Optional, no default; from GitHub Variables
      # build_argument_three: # Optional, no default; from GitHub Variables
    secrets:
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Optional (Current maximum of secrets that can be set =  6 secrets. Can be expanded)
      # docker_secret_1:
      # docker_secret_2:
      # docker_secret_3:
      # docker_secret_4:
      # docker_secret_5:
      # docker_secret_6:

  github-environment:
    uses: test-org-fanna/.github/.github/workflows/determine-environment.yml@main

# TODO(REP-2945): Move this step to the repository infra
# Should only be active for repower-django (add job to 'needs' in deploy-verify)
#  run-migrations:
#    uses: test-org-fanna/.github/.github/workflows/run-kube-migration.yml@main
#    needs: tag
#    with:
#      tag: ${{ needs.tag.outputs.tag }}

  deploy-verify-config:
    uses: test-org-fanna/.github/.github/workflows/kube-deploy-verify.yml@main
    needs: [github-environment, docker-with-config]
    with:
      # If there are multiple deployments for a single docker image, the container names can be specified here
      # Example:
      # Dockerfile 'hello-world' is responsible for the following deployments: foo, bar
      # the corresponding container_names are: "['foo', 'bar']"
      container_names: "['with-config-1', 'with-config-2']"
      docker_image_tag: ${{ needs.docker.outputs.image_tag }}
      environment: ${{ needs.github-environment.outputs.environment }}
    secrets: inherit

  deploy-verify-simple:
    uses: test-org-fanna/.github/.github/workflows/kube-deploy-verify.yml@main
    needs: [github-environment, docker-simple]
    with:
      # If there are multiple deployments for a single docker image, the container names can be specified here
      # Example:
      # Dockerfile 'hello-world' is responsible for the following deployments: foo, bar
      # the corresponding container_names are: "['foo', 'bar']"
      container_names: "['simple']"
      docker_image_tag: ${{ needs.docker.outputs.image_tag }}
      environment: ${{ needs.github-environment.outputs.environment }}
    secrets: inherit
