name: TAG

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - qa
      - main
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.github-tag.outputs.tag }}
    steps:
      # Checkout the repository with all commit history
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      # Automatically bump and tag with the latest SemVer formatted version.
      - name: Generate and push GitHub tag
        id: github-tag
        uses: anothrNick/github-tag-action@1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main, dev
          DEFAULT_BRANCH: dev
          DEFAULT_BUMP: none
          PRERELEASE: true