name: GitHub Tag, Docker publish build, SSH Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_run:
    workflows: [ "Run Pytest with Coverage, Check the Django Migrations and run the Sonar Analysis" ]
    types:
      - completed

jobs:
  deploy-run-check:
    if: ${{ contains(github.event.head_commit.message, '[merge]') || contains(github.event.pull_request.title, '[deploy]') }}
    runs-on: ubuntu-latest
    steps:
      - name: DEPLOY Run check
        run: echo "Deploy done"