name: Deploy
on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed

run-name: Deploy tag ... to .. by @${{ github.actor }}

jobs:
  check-deploy-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Check deploy trigger
        run: |
          IS_SUCCESS=${{ github.event_name == 'workflow_run' && contains(github.event.workflow_run.conclusion, 'success') }}
          IS_DEV=${{ contains(github.head_ref, 'dev') }}
          COMMIT_CONTAINS_DEPLOY=${{ contains(github.event.workflow_run.head_commit.message, '[deploy]') }}
          echo "is_success=$IS_SUCCESS" >> $GITHUB_OUTPUT
          echo "is_dev=$IS_DEV" >> $GITHUB_OUTPUT
          echo "commit_contains_dpeloy=$COMMIT_CONTAINS_DEPLOY" >> $GITHUB_OUTPUT

  generate-tag:
    needs: [check-deploy-trigger]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      IS_SUCCESS: ${{ needs.check-deploy-trigger.outputs.is_success }}
      IS_DEV: ${{ needs.check-deploy-trigger.outputs.is_dev }}
      COMMIT_CONTAINS_DEPLOY: ${{ needs.check-deploy-trigger.outputs.commit_contains_deploy }}
    if: ${{ env.IS_SUCCESS && (env.IS_DEV || env.COMMIT_CONTAINS_DEPLOY) }}
    steps:
      # Checkout the repository with all commit history
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      # Automatically bump and tag with the latest SemVer formatted version.
      - name: Generate and push GitHub tag
        id: github-tag
        uses: anothrNick/github-tag-action@1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main, dev
          DEFAULT_BRANCH: dev
          PRERELEASE: ${{ env.IS_DEV && env.COMMIT_CONTAINS_DEPLOY }}
