name: GitHub Tag, Docker publish build, SSH Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - release/**
      - hotfix/**
  pull_request:

jobs:
  should_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit message header
        id: get_commit_message
        run: |
          echo "${{ toJson(github.event.pull_request) }}" >> $GITHUB_STEP_SUMMARY
          git log --pretty=%B | head -n 10
          git show -s --format=%s
#          echo "${{ github.event.pull_request.head.sha }}" >> $GITHUB_STEP_SUMMARY
#          echo "${{ toJson(github) }}" >> $GITHUB_STEP_SUMMARY
  #          COMMIT_MESSAGE_HEADER=$(git log -1 --pretty=%B ${{ github.event.pull_request.head.sha }} | head -n 1)
#          echo "COMMIT_MESSAGE_HEADER=${COMMIT_MESSAGE_HEADER}" >> $GITHUB_ENV
#          if [[ $COMMIT_MESSAGE_HEADER == *"[deploy]"* || github.event_name != "pull_request" ]]; then
#            SHOULD_RUN=true
#          else
#            SHOULD_RUN=false
#          fi
#          echo "should_run=${SHOULD_RUN}" >> $GITHUB_OUTPUT
#
#      - name: Use commit message header
#        run: |
#          echo "The commit message header is: $COMMIT_MESSAGE_HEADER" >> $GITHUB_STEP_SUMMARY
#          echo "Should run: $COMMIT_MESSAGE_HEADER" >> $GITHUB_STEP_SUMMARY
#          echo "Workflow run: ${{ github.event.workflow_run.head_commit.message }}" >> $GITHUB_STEP_SUMMARY

  tag:
    if: github.event_name != 'pull_request' || contains(github.event.head_commit.message, '[deploy]')
    permissions:
      contents: write
    uses: test-org-fanna/.github/.github/workflows/generate-github-tag.yml@main

  # Only for the front-end; delete this job if you don't have a 'package.json'
  bump:
    if: github.event_name != 'pull_request' || contains(github.event.head_commit.message, '[deploy]')
    permissions:
      contents: write
    uses: test-org-fanna/.github/.github/workflows/bump-package-json.yml@main
    needs: tag
    with:
      tag: ${{ needs.tag.outputs.tag }}
      # node_version: # Optional, defaults to "20"
      # working_directory: # Optional, defaults to './'.

  # Repeat steps below if there are multiple Dockerfiles and/or docker-compose files

  docker:
    if: github.event_name != 'pull_request' || contains(github.event.head_commit.message, '[deploy]')
    uses: test-org-fanna/.github/.github/workflows/docker-build-and-push.yml@main
    needs: tag
    with:
      tag: ${{ needs.tag.outputs.tag }}
      docker_hub_username: ${{ vars.DOCKER_HUB_USERNAME }}
      dockerfile_name: Dockerfile.name
      # build_argument_one: # Optional, no default; from GitHub Variables
      # build_argument_two: # Optional, no default; from GitHub Variables
      # build_argument_three: # Optional, no default; from GitHub Variables
    secrets:
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Optional (Current maximum of secrets that can be set =  6 secrets. Can be expanded)
      # docker_secret_1:
      # docker_secret_2:
      # docker_secret_3:
      # docker_secret_4:
      # docker_secret_5:
      # docker_secret_6:

  environment:
    if: ${{ github.event_name != 'pull_request' }} || contains(github.event.head_commit.message, '[deploy]')
    uses: test-org-fanna/.github/.github/workflows/determine-environment.yml@main

  deploy:
    if: github.event_name != 'pull_request' || contains(github.event.head_commit.message, '[deploy]')
    needs: [ environment, docker, tag ]
    uses: test-org-fanna/.github/.github/workflows/deploy-docker-compose.yml@main
    with:
      environment: ${{ needs.environment.outputs.environment }}
      tag: ${{ needs.tag.outputs.tag }}
      # server_username: Optional, defaults to 'root'
      # docker-compose_remote_dir: Optional, defaults to '/root'
      docker-compose_file_path: 'nested-test/docker-compose.yml'
    secrets: inherit
