name: Deploy
on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed

run-name: Deploy tag ... to .. by @${{ github.actor }}

jobs:
  generate-tag:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      IS_SUCCESS: ${{ github.event_name == 'workflow_run' && contains(github.event.workflow_run.conclusion, 'success') }}
      IS_DEV: ${{ contains(github.head_ref, 'dev') }}
      COMMIT_CONTAINS_DEPLOY: ${{ contains(github.event.workflow_run.head_commit.message, '[deploy]') }}
    if: ${{ env.IS_SUCCESS && (env.IS_DEV || env.COMMIT_CONTAINS_DEPLOY) }}
    steps:
      # Checkout the repository with all commit history
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      # Automatically bump and tag with the latest SemVer formatted version.
      - name: Generate and push GitHub tag
        id: github-tag
        uses: anothrNick/github-tag-action@1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main, dev
          DEFAULT_BRANCH: dev
          PRERELEASE: ${{ env.IS_DEV && env.COMMIT_CONTAINS_DEPLOY }}
