name: Test
on:
  push:
    branches:
      - dev
      - hotfix**
  pull_request:
    branches-ignore:
      - main

jobs:
  yarn-check-lint-prettier-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Fake test
        run: echo "Test succeeded"

  determine-environment:
    name: Determine the GitHub environment
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve environment
        id: retrieve-environment
        run: |
          echo "Running on branch ${{ github.ref_name }}"
          if [[ "${{ github.ref_name }}" == "dev" && "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
            echo "env_name=prod" >> $GITHUB_OUTPUT
          else
            echo "env_name=dev" >> $GITHUB_OUTPUT
          fi
