name: Deploy with environment

on:
  workflow_dispatch:
  push:
#  pull_request:
#    branches:
#      - dev
#      - release/**
#      - hotfix/**

jobs:
  scp-docker-compose:
    name: Secure copy docker-compose to ${{ vars.HOST }}
    environment: prod
    runs-on: ubuntu-latest
    secrets:
      key: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Copy docker-compose file via SCPst
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.HOST }}
          username: root
          source: docker-compose.yml
          target: /root

  deploy-docker-compose:
    name: Deploy docker-compose via SSH
    needs: scp-docker-compose
    runs-on: ubuntu-latest
    secrets:
      key: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - name: SSH deployment with docker-compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.HOST }}
          script: |
            docker system prune --all --force
            DOCKER_COMPOSE_PATH=/root/docker-compose.yml
            docker-compose -f $DOCKER_COMPOSE_PATH pull
            docker-compose -f $DOCKER_COMPOSE_PATH up -d --force-recreate