name: Deploy with environment

on:
  workflow_dispatch:
  push:
#  pull_request:
#    branches:
#      - dev
#      - release/**
#      - hotfix/**

jobs:
  get-environment-secrets:
    name: Retrieve the secrets and variables set within a GitHub environment needed for the deploy steps
    id: get-environment-secrets
    environment: prod
    runs-on: ubuntu-latest
    outputs:
      host: ${{ steps.output-vars-secrets.outputs.host }}
      key: ${{ steps.output-vars-secrets.outputs.key }}

    steps:
      - name: Output variable and secrets
        id: output-vars-secrets
        run: |
          echo "host=${{ vars.HOST }}" >> GITHUB_OUTPUT
          echo "key=${{ secrets.KEYKEYKEY }}" >> GITHUB_OUTPUT

  scp-docker-compose:
    name: Secure copy docker-compose to server
    needs: get-environment-secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy docker-compose file via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ needs.get-environment-secrets.outputs.host }}
          username: root
          key: ${{ needs.get-environment-secrets.outputs.key }}
          source: docker-compose.yml
          target: /root

  deploy-docker-compose:
    name: Deploy docker-compose via SSH
    needs: [scp-docker-compose, get-environment-secrets]
    runs-on: ubuntu-latest
    steps:
      - name: SSH deployment with docker-compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ needs.get-environment-secrets.outputs.host }}
          username: root
          key: ${{ needs.get-environment-secrets.outputs.key }}
          script: |
            docker system prune --all --force
            DOCKER_COMPOSE_PATH=/root/docker-compose.yml
            docker-compose -f $DOCKER_COMPOSE_PATH pull 
            docker-compose -f $DOCKER_COMPOSE_PATH up -d --force-recreate