name: Test

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - closed
    branches-ignore:
      - main



jobs:
  test-run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Test run check
        run: echo "Test success"
