name: Deploy with environment

on:
  workflow_dispatch:
  push:
#  pull_request:
#    branches:
#      - dev
#      - release/**
#      - hotfix/**

jobs:
  deploy:
    uses: test-org-fanna/.github/.github/workflows/deploy-docker-compose.yml@main