name: Deploy with environment

on:
  workflow_dispatch:
  push:
#  pull_request:
#    branches:
#      - dev
#      - hotfix/**
#      - release/**

jobs:
  environment:
    uses: test-org-fanna/.github/.github/workflows/determine-environment.yml@main

  deploy:
    needs: environment
    uses: test-org-fanna/.github/.github/workflows/deploy-docker-compose.yml@main
    with:
      environment: ${{ needs.environment.outputs.environment }}
    secrets: inherit