name: Deploy with environment

on:
  workflow_dispatch:
  push:
#  pull_request:
#    branches:
#      - dev
#      - release/**
#      - hotfix/**

jobs:
  environment:
    uses: test-org-fanna/.github/.github/workflows/determine-environment.yml@main

  deploy:
    uses: test-org-fanna/.github/.github/workflows/deploy-docker-compose.yml@main
    needs: environment
    environment: ${{ needs.environment.outputs.environment }}
    with:
      host: ${{ vars.HOST }}
    secrets:
      key: ${{ secrets.SSH_PRIVATE_KEY }}