name: Yarn install, eslint, prettier and optionally publish and/or test with coverage

on:
  push:

jobs:
  analyze:
    runs-on: ubuntu-latest
    env:
      CI: true
      NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js with yarn cache
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'yarn'
          cache-dependency-path: ./yarn.lock

      - name: Install dependencies
        working_directory: vue-test
        run: yarn install --immutable

      - name: Check for outdated dependencies
        working_directory: vue-test
        continue-on-error: true
        run: |
          OUTDATED_CHECK=$(yarn run ncu)
          if [ $(echo "$OUTDATED_CHECK" | tail -n 1) != "All dependencies match the latest package versions :)" ]; then
            echo "<h2>:eyes: Outdated dependencies found</h2>" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "$OUTDATED_CHECK" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "<h3>It is recommended to run `yarn run ncu -u` for fast and non-interactive upgrades \
              or `yarn upgrade-interactive` to manually select upgrades</h3>" >> $GITHUB_STEP_SUMMARY
            exit 3
          fi

      - name: Yarn lint
        working_directory: vue-test
        run: yarn lint

      - name: Yarn prettier check
        working_directory: vue-test
        run: yarn prettier --check "{json-server,src}/**/*.{js,vue,json,html,css,md}"

      - name: Yarn tests with coverage
        working_directory: vue-test
        run: yarn test:coverage

      - name: Show test failures in the job summary
        working-directory: vue-test
        if: failure()
        run: |
          if [ -f coverage/clover.xml ]; then
            echo "<h2>:x: Tests Failed</h2>" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            cat coverage/clover.xml >> $GITHUB_STEP_SUMMARY
          fi   

      - name: Archive 'coverage.xml' report
        working_directory: vue-test
        uses: actions/upload-artifact@v4
        with:
          name: coverage.xml
          path: coverage/clover.xml
          if-no-files-found: 'error'