# Generated by Django 5.1.2 on 2024-10-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetRock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('birth_date', models.DateField()),
                ('mood', models.CharField(choices=[('HAPPY', 'Happy'), ('GRUMPY', 'Grumpy'), ('SLEEPY', 'Sleepy'), ('EXCITED', 'Excited')], default='HAPPY', max_length=10)),
                ('resting_spot', models.CharField(default='A soft pillow', max_length=255)),
                ('times_rolled', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pet Rock',
                'verbose_name_plural': 'Pet Rocks',
            },
        ),
    ]
